name: build
on:
  push:
    branches:
      - actions
jobs:
  build_latex:
    name: build-latex
    id: compile_tex_file
    uses: tsukuba-mas/platex-action@main
    with:
      LATEX_FILE_NAME: "wiss/wiss_template.tex"
